### ISSUE TITLE
VAMAS import fails for data processed in casa using range calibration.

### ISSUE THREAD

**Issue by sameyley** [FAIRmat-NFDI/pynxtools-xps#62]
Trying to import vamas files which were calibrated using range calibration fails due to https://github.com/FAIRmat-NFDI/pynxtools-xps/blob/42db18c72a88ad174733ad97790523ea97dfac09/src/pynxtools_xps/vms/casa_data_model.py#L95.

The line in the vamas file in these cases is e.g.:

Calib M = 280,281 A = 285 BE ADD

**Comment by lukaspie** [comment]
Dear @sameyley, thanks for testing out the reader with your data! I think I pretty much know what the problem is and will implement a fix relatively soon. I will let you know as soon as it is fixed. If you want, you could share one of your files with me so I can make sure that there won't be any other problems.

Note however, that the parsing of data processing from CasaXPS was only recently introduced and is still somewhat experimental. We are still working on updating our description of fitting in general (see https://github.com/FAIRmat-NFDI/nexus_definitions/pull/170 for the discussion on the data modeling), so this will probably still change a bit.

**Comment by sameyley** [comment]
Hi Lukas,
Here is a test file: [test_data.zip](https://github.com/user-attachments/files/15911477/test_data.zip). We also use a Kratos instrument, so this could also be useful for #61.

**Comment by ondracka** [comment]
@sameyley off topic here, but would you be willing to share your KRATOS ELM file?

**Comment by sameyley** [comment]
> @sameyley off topic here, but would you be willing to share your KRATOS ELN file?

I don't have one, sorry - just like you, I just tried importing the data without setting up an ELN. I doubt I will do one for now as my workflow is centred around VAMAS file format and I see that there are lots of parameters for nxmpes for which I do not have an answer at the moment. It's not a priority, I was just curious after seeing Lukas' presentation at ECASIA.

**Comment by ondracka** [comment]
I see, thanks. Yeah, I think it will be some work to get the ELN just right... unless I can catch some KRATOS technician when the next maintenance time comes :smile:
